### ISSUE TITLE
Newer version?

### ISSUE THREAD

**Issue by joyousrabbit** [cjweeks/tensorflow-cmake#12]
Hello, thanks for this great work.
Does it work only for 0.10 or the later version like 1.0.1 or 1.1.0?

**Comment by cjweeks** [comment]
Hello!
Currently support begins at 0.10 and should go continuously to the latest release.  I'm planning on adding support for 0.9 (which just requires some new logic in `protobuf.sh`) as well.  Have you encountered a problem with the version you are using?

**Comment by RoboEvangelist** [comment]
I have tensorflow 1.0.1, but when I build the external project I get an error saying that  both eigen and protobuf's tar.gz files cannot be opened, even though the protobuf.sh and eigen.sh can find both libraries inside my tensorflow root folders. Do you know what this issue is? Thanks

**Comment by HFTrader** [comment]
Post your log so we can see what's going on

**Comment by cjweeks** [comment]
Hello, there was a slight issue with TensorFlow 1.0.1 in this repository. I just cleared it up, but I'm not sure it existed when @RoboEvangelist posted.  Please let me know of any further support problems; I have been trying to make sure this repository works well with most recent versions.
