### ISSUE TITLE
protobuf.sh - command failed

### ISSUE THREAD

**Issue by eflavio** [cjweeks/tensorflow-cmake#15]
When I want to run the protobuf.sh script with `sudo ./protobuf.sh install ../tensorflow` I get the following output/error:

> Finding Protobuf version in ../tensorflow using method 0...
> Command` failed - script terminated

Any idea how to resolve that?

**Comment by eflavio** [comment]
I followed the error myself and finally realized that you have to change a variable in protobuf.sh:

BEFORE:

> HTTP_HEADER="native.http_archive\(\s"

NEW:

> HTTP_HEADER="patched_http_archive\(\s"

That helped.
Cheers

**Comment by MiloAnthony** [comment]
@eflavio I changed the code you mentioned ,but  the error is still exist. Which tensorflow version do you use? I used 1.0.1
