### ISSUE TITLE
eigen install

### ISSUE THREAD

**Issue by HFTrader** [cjweeks/tensorflow-cmake#17]
What is the point on installing Eigen under the hash? It makes it hard to use it the include afterwards. I would like to propose installing under ${INSTALL_DIR}/include only

from this:

    cmake -DCMAKE_INSTALL_PREFIX=${INSTALL_DIR}\
	  -DINCLUDE_INSTALL_DIR=${INSTALL_DIR}/include/eigen/eigen-eigen-${EIGEN_ARCHIVE_HASH} .. || fail

to this: 

    cmake -DCMAKE_INSTALL_PREFIX=${INSTALL_DIR} .. || fail

I am having to do a 2nd step of copying the includes recursively. 
Let me know your thoughts.

**Comment by cjweeks** [comment]
This was done in earlier versions of TensorFlow, and I experienced difficulties when trying to simply the system like you suggested.  However, for some time now TensorFlow has not used this convention, and I have abandoned it as well.  I am working to bring this repository back up to date with TensorFlow, and I believe the newest updates by default store Eigen in `<prefix>/include/eigen3`.
