### ISSUE TITLE
Nice work

### ISSUE THREAD

**Issue by AlexanderLitz** [cjweeks/tensorflow-cmake#2]
Note that on the examples documentation, you write:

./protobuf.sh genearte installed ~/git/tensorflow examples/install-project/cmake/Modules /usr/local

instead of 

./protobuf.sh generate installed ~/git/tensorflow examples/install-project/cmake/Modules /usr/local

**Comment by cjweeks** [comment]
Thank you for pointing this out; I have made the correction.
