### ISSUE TITLE
no such target '//tensorflow:libtensorflow_all.so'

### ISSUE THREAD

**Issue by mozi22** [cjweeks/tensorflow-cmake#22]
Hi, I am using Ubuntu 14.04. I tried to follow the instructions from here but i get an error saying

`ERROR: no such target '//tensorflow:libtensorflow_all.so': target 'libtensorflow_all.so' not declared in package 'tensorflow' (did you mean 'libtensorflow_cc.so'?) defined by /home/muazzam/mywork/python/tensorflow/tensorflow/BUILD. INFO: Elapsed time: 0.047s`

This error occurs when I use the following command from the repository documentation `bazel build tensorflow:libtensorflow_all.so`.

The `./configure` command is not generating this file and I dont know why.

anybody has any clues ?

**Comment by cjweeks** [comment]
I have a few questions and suggestions:
- Check the `(tensorflow-root)/tensorflow/BUILD` file to make sure the added build rule exists, where `tensorflow-root` is the root directory of your TensorfFow repository (in my case it is `~/git/tensorflow`).
- What directory are you calling `./configure` and `bazel build tensorflow:libtensorflow_all.so` from? You should be calling them from the root TensorfFow directory.

When you execute the `bazel build` command, Bazel looks for the build rule that you specified in the BUILD file of the directory you specified. If checking these items does not work, let me know.

**Comment by mozi22** [comment]
got it working. The problem was that I was copying the build rule inside the `(tensorflow-root)/BUILD` because the `(tensorflow-root)` is also called tensorflow in my case. It was confusing.
