### ISSUE TITLE
error: unable to parse version script file tensorflow/tf_version_script.lds

### ISSUE THREAD

**Issue by wujsy** [cjweeks/tensorflow-cmake#25]
hello,thanks for provide this project.
when I build tensorflow_all.so , I get an error like this 
"error: unable to open version script file tensorflow/tf_version_script.lds, that's no this file or directory"
"fatal error: unable to parse version script file tensorflow/tf_version_script.lds", 
but I can find this file in  the directory, and it seems normal. how can I fix this problem, please?@cjweeks

my env:
ubuntu 16.04
tensorflow 1.2
cuda 8.0
cudnn 5.1

**Comment by cjweeks** [comment]
I tried to build TensorFlow 1.2.0 using Ubuntu 16.04, and I encountered no errors.  Just to make sure nothing has happened to the `tf_version_scripts.lds` file, I would run `git status` to see if any changes were accidentally made.  Second, make sure that you have the correct read permissions set for `tf_version_scripts.lds`; perhaps Bazel is unable to open the file for this reason. What is the exact commit of TensorFlow and version of Bazel you are using (I am using `12f033df4c8fa3feb88ce936eb1581eaa92b303e` and `0.5.2` respectively).  I hope this helps.

**Comment by wujsy** [comment]
@cjweeks thanks for response, maybe I have broken the tf project unconsciously, I will check out what has happened, thanks again!

**Comment by cjweeks** [comment]
@wujsy Did this end up working?

**Comment by wujsy** [comment]
yes, I cloned anew tensorflow 1.2 and rebuild it ,there is no problem, thanks
