### ISSUE TITLE
Build with CUDA GPU support?

### ISSUE THREAD

**Issue by eyewy** [cjweeks/tensorflow-cmake#6]
Thanks, this works great for CPU. What should be added to build with GPU support? Using Bazel it is quite easy, just by adding "-c opt --config=cuda". Is there a similar switch for cmake?

**Comment by bgraf422** [comment]
If you add the cuda flag when you build the shared library you will get GPU support.  So the command in Step 1 should be:  bazel build -c opt --config=cuda tensorflow:libtensorflow_all.so.

When I first tried this command, I got an error message about a missing crosstool, similar to https://github.com/tensorflow/tensorflow/issues/4105.  I deleted the bazel cache folder (.cache/bazel/) and re-ran the ./configure script as recommended and then the above build command completed successfully
